# Generated by Django 5.0.6 on 2024-06-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='rating',
        ),
    ]
